### PR TITLE
STOR-1850: Rebase to upstream v1.15.0 for OCP 4.17

### PR DESCRIPTION
**Pull request by dfajmon**
Diff to upstream v1.15.0:
https://github.com/kubernetes-csi/csi-driver-smb/compare/v1.15.0...dfajmon:rebase-1.14.0

Changes between 1.13.0 (OCP 4.16) and 1.15.0 (OCP 4.17):
- https://github.com/kubernetes-csi/csi-driver-smb/pull/692
- https://github.com/kubernetes-csi/csi-driver-smb/pull/700
- https://github.com/kubernetes-csi/csi-driver-smb/pull/709
- https://github.com/kubernetes-csi/csi-driver-smb/pull/722
- https://github.com/kubernetes-csi/csi-driver-smb/pull/771
- https://github.com/kubernetes-csi/csi-driver-smb/pull/751
- https://github.com/kubernetes-csi/csi-driver-smb/pull/776

Full changelogs:
https://github.com/kubernetes-csi/csi-driver-smb/releases/tag/v1.14.0
https://github.com/kubernetes-csi/csi-driver-smb/releases/tag/v1.15.0

@openshift/storage

### CODE REVIEW

**Comment by RomanBednar** [comment]
@dfajmon Please correct the diff link, it should be: https://github.com/kubernetes-csi/csi-driver-smb/compare/v1.14.0...dfajmon:rebase-1.14.0

Also I think this repo is missing the `.snyk` file... @mpatlasov should we add it or is that intentional?

**Comment by mpatlasov** [comment]
> Also I think this repo is missing the .snyk file... @mpatlasov should we add it or is that intentional?

It was not intentional. Let's add .snyk to be uniform with other repos.

**Comment by mpatlasov** [comment]
@dfajmon , we forked `openshift/csi-driver-smb` from upstream at `6c12ee768` (Jan 25) *after* it was tagged with v1.14.0 (`7f74465a` on Jan 16). This means that all upstream commits between `7f74465a` and `6c12ee768` (which are currently present in our repo) will be lost if we merge this rebase PR. This may bring regressions :(

We can either cherry-pick all those commits from upstream and drop them on the next rebase, or we can simply wait for new tag in upstream (v1.15.0 ?). I'd prefer the latter because this rebase ([PR#11](https://github.com/openshift/csi-driver-smb/pull/11)) won't give us any new upstream fixes or improvements anyway.

**Comment by mpatlasov** [comment]
/hold
(per https://github.com/openshift/csi-driver-smb/pull/11#issuecomment-2195583109 )

**Comment by RomanBednar** [comment]
@dfajmon Based on the discussion above - when changing this rebase PR to `v1.15.0` please also add the `.snyk` file and amend to `UPSTREAM: <carry>: Add OpenShift files` commit. Just copy it from some other repo - there should be an exclude rule for vendor and tests dir.

**Comment by dfajmon** [comment]
@mpatlasov newly rebased with the tag 1.15.0
/unhold

**Comment by mpatlasov** [comment]
/lgtm
/approve
/label docs-approved
/label px-approved

Great job, thank you!

**Comment by Phaow** [comment]
/label qe-approved
Pre merge test passed with manually build driver image with the PR:
```console
$ oc rsh -c csi-driver smb-csi-driver-controller-5bb444444c-9zggf
sh-5.1# /bin/smbplugin --ver
Build Date: "2024-08-05T07:30:37Z"
Compiler: gc
Driver Name: smb.csi.k8s.io
Driver Version: v1.15.0
Git Commit: 8e26a1e4b731fab822f45a9d2766c34c02f17eb8
Go Version: go1.22.5 (Red Hat 1.22.5-1.el9) X:strictfipsruntime
Platform: linux/amd64

# E2E Regression tests all looks good
$ go test -v -timeout=0 ./test/e2e
Ran 12 of 13 Specs in 323.231 seconds
SUCCESS! -- 12 Passed | 0 Failed | 0 Pending | 1 Skipped
```

**Pull request merged**
