### PR TITLE
STOR-2006: Rebase to upstream v1.16.0 for OCP 4.18

### PR DESCRIPTION
**Pull request by dfajmon**
Issue link:
https://issues.redhat.com/browse/STOR-2006

Diff to upstream v1.14.0:
https://github.com/kubernetes-csi/csi-driver-smb/compare/v1.16.0...dfajmon:rebase-1.16.0

Changes between 1.14.0 (OCP 4.17) and 1.16.0 (OCP 4.18):
1.15.0
- https://github.com/kubernetes-csi/csi-driver-smb/pull/771
- https://github.com/kubernetes-csi/csi-driver-smb/pull/799
- https://github.com/kubernetes-csi/csi-driver-smb/pull/771
- https://github.com/kubernetes-csi/csi-driver-smb/pull/745
- https://github.com/kubernetes-csi/csi-driver-smb/pull/739

1.16.0
- https://github.com/kubernetes-csi/csi-driver-smb/pull/806
- https://github.com/kubernetes-csi/csi-driver-smb/pull/811
- https://github.com/kubernetes-csi/csi-driver-smb/pull/827
- https://github.com/kubernetes-csi/csi-driver-smb/pull/831
- https://github.com/kubernetes-csi/csi-driver-smb/pull/824

Full changelogs:
https://github.com/kubernetes-csi/csi-driver-smb/releases/tag/v1.15.0
https://github.com/kubernetes-csi/csi-driver-smb/releases/tag/v1.16.0

@openshift/storage

### CODE REVIEW

**Comment by Phaow** [comment]
Pre merge test passed with manual build driver/operator/bundle/index with this PR. But after https://github.com/kubernetes-csi/csi-driver-smb/pull/817 the e2e will install the helm upstream driver version by default in `BeforeSuite`, it will impact our presubmit job `smb-operator-e2e-extended`, try to make it compatible in https://github.com/kubernetes-csi/csi-driver-smb/pull/854 .
```console
$ oc get csv
NAME                              DISPLAY                        VERSION   REPLACES   PHASE
smb-csi-driver-operator.v4.18.0   CIFS/SMB CSI Driver Operator   4.18.0               Succeeded
$ oc rsh -c csi-driver smb-csi-driver-controller-856986f55c-jhj4l
sh-5.1# /bin/smbplugin -ver
Build Date: "2024-09-30T06:23:32Z"
Compiler: gc
Driver Name: smb.csi.k8s.io
Driver Version: v1.16.0
Git Commit: f46104191bf7fbf7907f0b0fac4f419fa75195fa
Go Version: go1.22.5 (Red Hat 1.22.5-1.el9) X:strictfipsruntime
Platform: linux/amd64

$ go test -v -timeout=0 ./test/e2e -ginkgo.v -ginkgo.timeout=1h
Ran 12 of 13 Specs in 632.966 seconds
SUCCESS! -- 12 Passed | 0 Failed | 0 Pending | 1 Skipped
You're using deprecated Ginkgo functionality:
=============================================
  Support for custom reporters has been removed in V2.  Please read the documentation linked to below for Ginkgo's new behavior and for a migration path:
  Learn more at: https://onsi.github.io/ginkgo/MIGRATING_TO_V2#removed-custom-reporters

To silence deprecations that can be silenced set the following environment variable:
  ACK_GINKGO_DEPRECATIONS=2.17.1

--- PASS: TestE2E (632.97s)
PASS
ok      github.com/kubernetes-csi/csi-driver-smb/test/e2e       633.791s
```

**Comment by dfajmon** [comment]
the https://github.com/kubernetes-csi/csi-driver-smb/pull/854 has been merged can we follow up with this PR?
@Phaow

**Comment by Phaow** [comment]
> the [kubernetes-csi#854](https://github.com/kubernetes-csi/csi-driver-smb/pull/854) has been merged can we follow up with this PR? @Phaow

Sure, sorry for late reply, just back from holiday.

**Pull request merged**
